const GRID_SIZE = 100;
const NUM_APPLES = 15;
const MAX_PLAYERS = 10;

const APPLE_LIFETIME = 20000;
const SPECIAL_LIFETIME = 12000;
const MINE_LIFETIME = 15000;
const BLACK_HOLE_LIFETIME = 20000;

const DIRECTION_COOLDOWN_MS = 50;
const CHAT_COOLDOWN_MS = 1500;
const MAX_CHAT_LENGTH = 60;
const MAX_PLAYER_NAME_LENGTH = 20;

module.exports = {
    GRID_SIZE,
    NUM_APPLES,
    MAX_PLAYERS,
    APPLE_LIFETIME,
    SPECIAL_LIFETIME,
    MINE_LIFETIME,
    BLACK_HOLE_LIFETIME,
    DIRECTION_COOLDOWN_MS,
    CHAT_COOLDOWN_MS,
    MAX_CHAT_LENGTH,
    MAX_PLAYER_NAME_LENGTH
};
